/*
Copyright 2026 Date Huang.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package bootd

import (
	"fmt"
	"net"
	"path/filepath"
	"slices"
	"strings"
)

// kezioTag is the dnsmasq tag the MAC gate pivots on: the hostsfile
// sets it per allowed MAC (see RenderHostsfile) and the rendered config
// only hands out PXE boot info to requests carrying it.
const kezioTag = "kezio"

// HostsfileName and leasefileName are the file names RenderDnsmasqConf
// points dnsmasq at inside the run directory. The hostsfile is the one
// file rewritten at runtime (see Dnsmasq.SetAllowedMACs): dnsmasq
// re-reads dhcp-hostsfile on SIGHUP but never the main config, so
// everything dynamic must live here and everything else in the config
// is fixed for the process's lifetime.
const (
	HostsfileName = "dhcp-hosts.conf"
	leasefileName = "dnsmasq.leases"
)

// HostsfilePath returns the path of the dhcp-hostsfile inside runDir.
func HostsfilePath(runDir string) string {
	return filepath.Join(runDir, HostsfileName)
}

// RenderDnsmasqConf renders the complete dnsmasq configuration for cfg,
// with dnsmasq's writable files (hostsfile, leasefile) placed under
// runDir. It is a pure function: no file is touched and no process
// consulted, so every rendered line is unit-testable.
//
// The rendered instance is a proxyDHCP server (dhcp-range ...,proxy):
// it never assigns addresses, it only answers the PXE portion of the
// exchange on ports 67 and 4011. Lease assignment stays with the
// site's own DHCP server, optionally reached via dhcp-relay (see
// Config.RelayServerIP).
//
// The MAC gate works through dnsmasq tags: dhcp-hostsfile sets
// tag:kezio on enrolled MACs, pxe-service only matches tag:kezio, and
// dhcp-ignore=tag:!kezio drops every other request entirely. That last
// line is what suppresses the content-free proxy OFFER dnsmasq would
// otherwise still broadcast to unknown MACs (an offer carrying no
// boot file, but enough for a strange firmware to latch onto);
// lab-verified: with dhcp-ignore in place a denied MAC receives
// nothing from bootd on either port 67 or 4011, while dhcp-relay
// forwarding for that same MAC keeps working - dnsmasq relays before
// its local DHCP engine evaluates dhcp-ignore, so relayed lease
// OFFERs still reach denied clients unharmed.
//
// pxe-service names x86-64_EFI as the client system architecture:
// lab-verified as the spelling that makes dnsmasq answer an arch-7
// (RFC 4578 EFI x86-64, what EDK2 firmware sends) client's port-4011
// REQUEST with the boot file in the BOOTP file field, via dnsmasq's
// UEFI PXE workaround. BC_EFI and a numeric 9 instead produce a PXE
// boot menu UEFI firmware does not process.
//
// TFTP stays deliberately absent (no enable-tftp): artifact serving
// remains the in-process pin/tftp server (tftp.go), which allowlists
// exactly two file names and rejects path traversal - dnsmasq's TFTP
// would serve anything under tftp-root and add nothing but a second
// code path to the same directory.
func RenderDnsmasqConf(cfg Config, runDir string) (string, error) {
	cfg = cfg.withDefaults()

	serverIP := cfg.ServerIP.To4()
	if serverIP == nil {
		return "", fmt.Errorf("ServerIP %v is not a valid IPv4 address", cfg.ServerIP)
	}
	if cfg.ProvisioningNet == nil {
		return "", fmt.Errorf("ProvisioningNet is required")
	}
	network := cfg.ProvisioningNet.IP.Mask(cfg.ProvisioningNet.Mask)
	if network.To4() == nil {
		return "", fmt.Errorf("ProvisioningNet %v is not an IPv4 network", cfg.ProvisioningNet)
	}
	mask := net.IP(cfg.ProvisioningNet.Mask)
	if len(mask) != net.IPv4len {
		return "", fmt.Errorf("ProvisioningNet %v does not carry an IPv4 netmask", cfg.ProvisioningNet)
	}

	nextServer := cfg.NextServerIP.To4()
	if nextServer == nil {
		nextServer = serverIP
	}

	var b strings.Builder
	b.WriteString("# Generated by kezio-bootd - do not edit.\n")
	b.WriteString("# dnsmasq re-reads only dhcp-hostsfile on SIGHUP; any change here\n")
	b.WriteString("# requires a dnsmasq restart (bootd restarts it on crash only).\n")
	// port=0 disables dnsmasq's DNS server entirely - bootd wraps
	// dnsmasq for DHCP alone.
	b.WriteString("port=0\n")
	// log-dhcp: per-request decision logging, forwarded into bootd's
	// own log stream by the supervisor (see Dnsmasq.Start) - the
	// equivalent of the per-packet outcome logging the previous
	// in-process DHCP responder had.
	b.WriteString("log-dhcp\n")
	if cfg.Interface != "" {
		b.WriteString("bind-interfaces\n")
		fmt.Fprintf(&b, "interface=%s\n", cfg.Interface)
	}
	fmt.Fprintf(&b, "dhcp-leasefile=%s\n", filepath.Join(runDir, leasefileName))
	fmt.Fprintf(&b, "dhcp-range=%s,proxy,%s\n", network, mask)
	fmt.Fprintf(&b, "dhcp-hostsfile=%s\n", HostsfilePath(runDir))
	if cfg.AnswerAll {
		// No tag guard and no dhcp-ignore: every PXE client is
		// answered - see Config.AnswerAll for when that trade is
		// acceptable.
		fmt.Fprintf(&b, "pxe-service=x86-64_EFI,\"kezio network boot\",%s,%s\n", cfg.BootFilename, nextServer)
	} else {
		fmt.Fprintf(&b, "pxe-service=tag:%s,x86-64_EFI,\"kezio network boot\",%s,%s\n", kezioTag, cfg.BootFilename, nextServer)
		fmt.Fprintf(&b, "dhcp-ignore=tag:!%s\n", kezioTag)
	}
	if cfg.RelayServerIP != nil {
		relayTo := cfg.RelayServerIP.To4()
		if relayTo == nil {
			return "", fmt.Errorf("RelayServerIP %v is not a valid IPv4 address", cfg.RelayServerIP)
		}
		fmt.Fprintf(&b, "dhcp-relay=%s,%s\n", serverIP, relayTo)
	}
	// dhcp-no-override: keep the boot file and server name in the
	// BOOTP header fields (file/sname) instead of moving them into
	// options 67/66 - the header fields are what PXE firmware reads.
	b.WriteString("dhcp-no-override\n")
	return b.String(), nil
}

// RenderHostsfile renders the dhcp-hostsfile contents for the given
// allowed MACs: one "<mac>,set:kezio" line per MAC, sorted and
// deduplicated so identical MAC sets always render byte-identical
// (letting the supervisor skip a rewrite-plus-SIGHUP when nothing
// changed). An empty or nil macs renders an empty file - the
// fail-secure state in which no machine receives boot info.
func RenderHostsfile(macs []string) string {
	if len(macs) == 0 {
		return ""
	}
	sorted := slices.Clone(macs)
	slices.Sort(sorted)
	sorted = slices.Compact(sorted)
	var b strings.Builder
	for _, mac := range sorted {
		fmt.Fprintf(&b, "%s,set:%s\n", mac, kezioTag)
	}
	return b.String()
}
