---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kezio-kojuro-date-v1alpha3-deployrun
  failurePolicy: Fail
  name: vdeployrun-v1alpha3.kb.io
  rules:
  - apiGroups:
    - kezio.kojuro.date
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployruns
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kezio-kojuro-date-v1alpha3-image
  failurePolicy: Fail
  name: vimage-v1alpha3.kb.io
  rules:
  - apiGroups:
    - kezio.kojuro.date
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - images
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kezio-kojuro-date-v1alpha3-machine
  failurePolicy: Fail
  name: vmachine-v1alpha3.kb.io
  rules:
  - apiGroups:
    - kezio.kojuro.date
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - machines
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kezio-kojuro-date-v1alpha3-machinehardware
  failurePolicy: Fail
  name: vmachinehardware-v1alpha3.kb.io
  rules:
  - apiGroups:
    - kezio.kojuro.date
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - machinehardwares
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kezio-kojuro-date-v1alpha3-partitioncontent
  failurePolicy: Fail
  name: vpartitioncontent-v1alpha3.kb.io
  rules:
  - apiGroups:
    - kezio.kojuro.date
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - partitioncontents
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kezio-kojuro-date-v1alpha3-posthook
  failurePolicy: Fail
  name: vposthook-v1alpha3.kb.io
  rules:
  - apiGroups:
    - kezio.kojuro.date
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - posthooks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kezio-kojuro-date-v1alpha3-site
  failurePolicy: Fail
  name: vsite-v1alpha3.kb.io
  rules:
  - apiGroups:
    - kezio.kojuro.date
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - sites
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kezio-kojuro-date-v1alpha3-subnet
  failurePolicy: Fail
  name: vsubnet-v1alpha3.kb.io
  rules:
  - apiGroups:
    - kezio.kojuro.date
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - subnets
  sideEffects: None
