apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: kezio
    app.kubernetes.io/component: ingest
    app.kubernetes.io/managed-by: kustomize
  name: ingest
  namespace: system
