resources:
- monitor.yaml

# [PROMETHEUS-WITH-CERTS] Configures the ServiceMonitor to reference
# cert-manager certs. Also uncomment the [METRICS-WITH-CERTS] patch in
# config/default/kustomization.yaml to mount "metrics-server-cert".
#patches:
#  - path: monitor_tls_patch.yaml
#    target:
#      kind: ServiceMonitor
