# Not used by kezio itself; a helper for cluster admins delegating
# permissions. Grants full ('*') access over images.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kezio
    app.kubernetes.io/managed-by: kustomize
  name: image-admin-role
rules:
- apiGroups:
  - kezio.kojuro.date
  resources:
  - images
  verbs:
  - '*'
- apiGroups:
  - kezio.kojuro.date
  resources:
  - images/status
  verbs:
  - get
