# Not used by kezio itself; a helper for users who manage images but
# should not control RBAC.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kezio
    app.kubernetes.io/managed-by: kustomize
  name: image-editor-role
rules:
- apiGroups:
  - kezio.kojuro.date
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kezio.kojuro.date
  resources:
  - images/status
  verbs:
  - get
