---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kezio.kojuro.date
  resources:
  - deployruns
  - machinehardwares
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kezio.kojuro.date
  resources:
  - deployruns/finalizers
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - kezio.kojuro.date
  resources:
  - deployruns/status
  - machines/status
  verbs:
  - get
  - patch
  - update
