apiVersion: kezio.kojuro.date/v1alpha3
kind: Site
metadata:
  labels:
    app.kubernetes.io/name: kezio
    app.kubernetes.io/managed-by: kustomize
  name: site-sample
spec:
  seederSubnetRef:
    name: subnet-sample
  tracker:
    ip: 192.0.2.3
