apiVersion: kezio.kojuro.date/v1alpha1
kind: Image
metadata:
  labels:
    app.kubernetes.io/name: kezio
    app.kubernetes.io/managed-by: kustomize
  name: image-sample
spec:
  source:
    url: https://example.com/images/ubuntu-2404-golden.qcow2
    format: qcow2
    checksum: sha256:0000000000000000000000000000000000000000000000000000000000000000
  bootable: true
  osFamily: Linux
