apiVersion: kezio.kojuro.date/v1alpha2
kind: Subnet
metadata:
  labels:
    app.kubernetes.io/name: kezio
    app.kubernetes.io/managed-by: kustomize
  name: subnet-sample
spec:
  siteRef:
    name: site-sample
  cidr: 192.0.2.0/24
  bootdServerIP: 192.0.2.2
  bootdNetworkRef:
    name: bootd-net-sample
  dhcp:
    mode: proxy
