apiVersion: kezio.kojuro.date/v1alpha3
kind: PostHook
metadata:
  labels:
    app.kubernetes.io/name: kezio
    app.kubernetes.io/managed-by: kustomize
  name: posthook-sample
spec:
  params:
    - name: hostname
  steps:
    - script:
        script: |
          #!/bin/sh
          hostnamectl set-hostname {{ .hostname }}
