apiVersion: kezio.kojuro.date/v1alpha1
kind: PostHook
metadata:
  labels:
    app.kubernetes.io/name: kezio
    app.kubernetes.io/managed-by: kustomize
  name: regen-initramfs
spec:
  params:
    - name: kernelArg
      default: ""
  steps:
    - chrootScript:
        script: |
          update-initramfs -u -k all
          echo "{{ .kernelArg }}" >> /etc/kernel/cmdline.d/kezio.conf
        timeoutSeconds: 300
    - script:
        configMapRef:
          name: notify-cmdb
          key: run.sh
        timeoutSeconds: 60
