// This file mirrors the gRPC contract upstream ezio serves. It is copied
// rather than referenced so that kezio's stub generation does not depend
// on checking out ezio's source tree. Keep it byte-for-byte in sync with
// upstream except for the go_package option added below; upstream owns
// the wire contract.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ezio.proto

package ezioapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EZIO_Shutdown_FullMethodName         = "/ezio.EZIO/Shutdown"
	EZIO_GetTorrentStatus_FullMethodName = "/ezio.EZIO/GetTorrentStatus"
	EZIO_AddTorrent_FullMethodName       = "/ezio.EZIO/AddTorrent"
	EZIO_PauseTorrent_FullMethodName     = "/ezio.EZIO/PauseTorrent"
	EZIO_ResumeTorrent_FullMethodName    = "/ezio.EZIO/ResumeTorrent"
	EZIO_GetVersion_FullMethodName       = "/ezio.EZIO/GetVersion"
)

// EZIOClient is the client API for EZIO service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EZIOClient interface {
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	GetTorrentStatus(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateStatus, error)
	AddTorrent(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	PauseTorrent(ctx context.Context, in *PauseTorrentRequest, opts ...grpc.CallOption) (*PauseTorrentResponse, error)
	ResumeTorrent(ctx context.Context, in *ResumeTorrentRequest, opts ...grpc.CallOption) (*ResumeTorrentResponse, error)
	GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type eZIOClient struct {
	cc grpc.ClientConnInterface
}

func NewEZIOClient(cc grpc.ClientConnInterface) EZIOClient {
	return &eZIOClient{cc}
}

func (c *eZIOClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, EZIO_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eZIOClient) GetTorrentStatus(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStatus)
	err := c.cc.Invoke(ctx, EZIO_GetTorrentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eZIOClient) AddTorrent(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, EZIO_AddTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eZIOClient) PauseTorrent(ctx context.Context, in *PauseTorrentRequest, opts ...grpc.CallOption) (*PauseTorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseTorrentResponse)
	err := c.cc.Invoke(ctx, EZIO_PauseTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eZIOClient) ResumeTorrent(ctx context.Context, in *ResumeTorrentRequest, opts ...grpc.CallOption) (*ResumeTorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeTorrentResponse)
	err := c.cc.Invoke(ctx, EZIO_ResumeTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eZIOClient) GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, EZIO_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EZIOServer is the server API for EZIO service.
// All implementations must embed UnimplementedEZIOServer
// for forward compatibility.
type EZIOServer interface {
	Shutdown(context.Context, *Empty) (*Empty, error)
	GetTorrentStatus(context.Context, *UpdateRequest) (*UpdateStatus, error)
	AddTorrent(context.Context, *AddRequest) (*AddResponse, error)
	PauseTorrent(context.Context, *PauseTorrentRequest) (*PauseTorrentResponse, error)
	ResumeTorrent(context.Context, *ResumeTorrentRequest) (*ResumeTorrentResponse, error)
	GetVersion(context.Context, *Empty) (*VersionResponse, error)
	mustEmbedUnimplementedEZIOServer()
}

// UnimplementedEZIOServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEZIOServer struct{}

func (UnimplementedEZIOServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedEZIOServer) GetTorrentStatus(context.Context, *UpdateRequest) (*UpdateStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTorrentStatus not implemented")
}
func (UnimplementedEZIOServer) AddTorrent(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTorrent not implemented")
}
func (UnimplementedEZIOServer) PauseTorrent(context.Context, *PauseTorrentRequest) (*PauseTorrentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseTorrent not implemented")
}
func (UnimplementedEZIOServer) ResumeTorrent(context.Context, *ResumeTorrentRequest) (*ResumeTorrentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeTorrent not implemented")
}
func (UnimplementedEZIOServer) GetVersion(context.Context, *Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedEZIOServer) mustEmbedUnimplementedEZIOServer() {}
func (UnimplementedEZIOServer) testEmbeddedByValue()              {}

// UnsafeEZIOServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EZIOServer will
// result in compilation errors.
type UnsafeEZIOServer interface {
	mustEmbedUnimplementedEZIOServer()
}

func RegisterEZIOServer(s grpc.ServiceRegistrar, srv EZIOServer) {
	// If the following call pancis, it indicates UnimplementedEZIOServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EZIO_ServiceDesc, srv)
}

func _EZIO_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EZIOServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EZIO_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EZIOServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EZIO_GetTorrentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EZIOServer).GetTorrentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EZIO_GetTorrentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EZIOServer).GetTorrentStatus(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EZIO_AddTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EZIOServer).AddTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EZIO_AddTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EZIOServer).AddTorrent(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EZIO_PauseTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EZIOServer).PauseTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EZIO_PauseTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EZIOServer).PauseTorrent(ctx, req.(*PauseTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EZIO_ResumeTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EZIOServer).ResumeTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EZIO_ResumeTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EZIOServer).ResumeTorrent(ctx, req.(*ResumeTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EZIO_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EZIOServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EZIO_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EZIOServer).GetVersion(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// EZIO_ServiceDesc is the grpc.ServiceDesc for EZIO service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EZIO_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ezio.EZIO",
	HandlerType: (*EZIOServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shutdown",
			Handler:    _EZIO_Shutdown_Handler,
		},
		{
			MethodName: "GetTorrentStatus",
			Handler:    _EZIO_GetTorrentStatus_Handler,
		},
		{
			MethodName: "AddTorrent",
			Handler:    _EZIO_AddTorrent_Handler,
		},
		{
			MethodName: "PauseTorrent",
			Handler:    _EZIO_PauseTorrent_Handler,
		},
		{
			MethodName: "ResumeTorrent",
			Handler:    _EZIO_ResumeTorrent_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _EZIO_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ezio.proto",
}
