# Not intended to run standalone - depends on service name/namespace from
# config/default.
resources:
- bases/kezio.kojuro.date_images.yaml
- bases/kezio.kojuro.date_posthooks.yaml
- bases/kezio.kojuro.date_machines.yaml
- bases/kezio.kojuro.date_imagelayouts.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
