//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployRun) DeepCopyInto(out *DeployRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployRun.
func (in *DeployRun) DeepCopy() *DeployRun {
	if in == nil {
		return nil
	}
	out := new(DeployRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeployRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployRunList) DeepCopyInto(out *DeployRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeployRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployRunList.
func (in *DeployRunList) DeepCopy() *DeployRunList {
	if in == nil {
		return nil
	}
	out := new(DeployRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeployRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployRunSpec) DeepCopyInto(out *DeployRunSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployRunSpec.
func (in *DeployRunSpec) DeepCopy() *DeployRunSpec {
	if in == nil {
		return nil
	}
	out := new(DeployRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployRunStatus) DeepCopyInto(out *DeployRunStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployRunStatus.
func (in *DeployRunStatus) DeepCopy() *DeployRunStatus {
	if in == nil {
		return nil
	}
	out := new(DeployRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Machine) DeepCopyInto(out *Machine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Machine.
func (in *Machine) DeepCopy() *Machine {
	if in == nil {
		return nil
	}
	out := new(Machine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Machine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineBMC) DeepCopyInto(out *MachineBMC) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineBMC.
func (in *MachineBMC) DeepCopy() *MachineBMC {
	if in == nil {
		return nil
	}
	out := new(MachineBMC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineDataImage) DeepCopyInto(out *MachineDataImage) {
	*out = *in
	out.ImageRef = in.ImageRef
	if in.TargetDisk != nil {
		in, out := &in.TargetDisk, &out.TargetDisk
		*out = new(TargetDiskHints)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineDataImage.
func (in *MachineDataImage) DeepCopy() *MachineDataImage {
	if in == nil {
		return nil
	}
	out := new(MachineDataImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineEzioTuning) DeepCopyInto(out *MachineEzioTuning) {
	*out = *in
	if in.CacheSizeMB != nil {
		in, out := &in.CacheSizeMB, &out.CacheSizeMB
		*out = new(int32)
		**out = **in
	}
	if in.AioThreads != nil {
		in, out := &in.AioThreads, &out.AioThreads
		*out = new(int32)
		**out = **in
	}
	if in.MaxUploads != nil {
		in, out := &in.MaxUploads, &out.MaxUploads
		*out = new(int32)
		**out = **in
	}
	if in.MaxConnections != nil {
		in, out := &in.MaxConnections, &out.MaxConnections
		*out = new(int32)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineEzioTuning.
func (in *MachineEzioTuning) DeepCopy() *MachineEzioTuning {
	if in == nil {
		return nil
	}
	out := new(MachineEzioTuning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineHardware) DeepCopyInto(out *MachineHardware) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineHardware.
func (in *MachineHardware) DeepCopy() *MachineHardware {
	if in == nil {
		return nil
	}
	out := new(MachineHardware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineHardware) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineHardwareList) DeepCopyInto(out *MachineHardwareList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineHardware, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineHardwareList.
func (in *MachineHardwareList) DeepCopy() *MachineHardwareList {
	if in == nil {
		return nil
	}
	out := new(MachineHardwareList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineHardwareList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineHardwareSpec) DeepCopyInto(out *MachineHardwareSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineHardwareSpec.
func (in *MachineHardwareSpec) DeepCopy() *MachineHardwareSpec {
	if in == nil {
		return nil
	}
	out := new(MachineHardwareSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineHardwareStatus) DeepCopyInto(out *MachineHardwareStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineHardwareStatus.
func (in *MachineHardwareStatus) DeepCopy() *MachineHardwareStatus {
	if in == nil {
		return nil
	}
	out := new(MachineHardwareStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineList) DeepCopyInto(out *MachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Machine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineList.
func (in *MachineList) DeepCopy() *MachineList {
	if in == nil {
		return nil
	}
	out := new(MachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineSpec) DeepCopyInto(out *MachineSpec) {
	*out = *in
	out.BMC = in.BMC
	if in.ImageRef != nil {
		in, out := &in.ImageRef, &out.ImageRef
		*out = new(NameRef)
		**out = **in
	}
	if in.DataImages != nil {
		in, out := &in.DataImages, &out.DataImages
		*out = make([]MachineDataImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TargetDisk != nil {
		in, out := &in.TargetDisk, &out.TargetDisk
		*out = new(TargetDiskHints)
		(*in).DeepCopyInto(*out)
	}
	out.SubnetRef = in.SubnetRef
	if in.PostHookRefs != nil {
		in, out := &in.PostHookRefs, &out.PostHookRefs
		*out = make([]NameRef, len(*in))
		copy(*out, *in)
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Ezio != nil {
		in, out := &in.Ezio, &out.Ezio
		*out = new(MachineEzioTuning)
		(*in).DeepCopyInto(*out)
	}
	if in.ClaimRef != nil {
		in, out := &in.ClaimRef, &out.ClaimRef
		*out = new(NameRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineSpec.
func (in *MachineSpec) DeepCopy() *MachineSpec {
	if in == nil {
		return nil
	}
	out := new(MachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineStatus) DeepCopyInto(out *MachineStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineStatus.
func (in *MachineStatus) DeepCopy() *MachineStatus {
	if in == nil {
		return nil
	}
	out := new(MachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NameRef) DeepCopyInto(out *NameRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NameRef.
func (in *NameRef) DeepCopy() *NameRef {
	if in == nil {
		return nil
	}
	out := new(NameRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetDiskHints) DeepCopyInto(out *TargetDiskHints) {
	*out = *in
	if in.MinSizeGigabytes != nil {
		in, out := &in.MinSizeGigabytes, &out.MinSizeGigabytes
		*out = new(int64)
		**out = **in
	}
	if in.MaxSizeGigabytes != nil {
		in, out := &in.MaxSizeGigabytes, &out.MaxSizeGigabytes
		*out = new(int64)
		**out = **in
	}
	if in.Rotational != nil {
		in, out := &in.Rotational, &out.Rotational
		*out = new(bool)
		**out = **in
	}
	if in.SlotNumber != nil {
		in, out := &in.SlotNumber, &out.SlotNumber
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetDiskHints.
func (in *TargetDiskHints) DeepCopy() *TargetDiskHints {
	if in == nil {
		return nil
	}
	out := new(TargetDiskHints)
	in.DeepCopyInto(out)
	return out
}
